name: Deployment pipeline

on: 
  push: 
    branches: 
      - main

jobs:
  deploy: 
    runs-on: ubuntu-latest
    steps:  
      - uses: actions/checkout@v3 # se usa para clonar el repositorio
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn install